#!/usr/bin/env python3
"""
Push the current branch and open a pull request via the GitHub API.

Usage:
    python tools/docs/gitops/open_pr.py [--bundle-root ./bundle]

Environment variables:
    GITHUB_TOKEN      - Required; GitHub token with repo write access
    GITHUB_REPOSITORY - Required; owner/repo (e.g. JeffSteinbok/octo-docs)
"""

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path

from docs.gitops.exceptions import GitCommandError, GitHubAPIError, GitOpsConfigError

_REQUEST_TIMEOUT = 30  # seconds for all GitHub API calls
_PR_CREATE_RETRIES = 3
_PR_RETRY_DELAY = 5  # seconds between retries


def _api_request(url: str, token: str, *, method: str = "GET",
                 payload: dict | None = None) -> dict:
    """Make a GitHub API request with timeout and consistent error handling."""
    import urllib.request
    import urllib.error

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    data = None
    if payload is not None:
        headers["Content-Type"] = "application/json"
        data = json.dumps(payload).encode("utf-8")

    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=_REQUEST_TIMEOUT) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        raise GitHubAPIError(method, exc.code, exc.reason) from exc
    except urllib.error.URLError as exc:
        raise GitHubAPIError(method, detail=str(exc.reason)) from exc


def _get_current_branch() -> str:
    result = subprocess.run(
        ["git", "rev-parse", "--abbrev-ref", "HEAD"],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise GitCommandError("git rev-parse", result.stderr)
    return result.stdout.strip()


def _push_branch(branch: str) -> None:
    result = subprocess.run(
        ["git", "push", "--set-upstream", "origin", branch],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise GitCommandError("git push", result.stderr)


def _build_pr_body(manifest: dict, changed_pages: list) -> str:
    """
    Build the pull request body from bundle metadata.

    Args:
        manifest: Parsed manifest.json dict with keys 'commit', 'bundle_version', 'generated_at'
        changed_pages: List of page IDs that were regenerated

    Returns:
        Formatted markdown string for the PR body
    """
    commit = manifest.get("commit", "unknown")
    version = manifest.get("bundle_version", "unknown")
    generated_at = manifest.get("generated_at", "unknown")

    pages_list = "\n".join(f"- `{p}`" for p in changed_pages) if changed_pages else "_none_"

    return f"""## Generated Documentation Update

| Field | Value |
|-------|-------|
| Bundle commit | `{commit}` |
| Bundle version | `{version}` |
| Generated at | `{generated_at}` |

### Regenerated pages

{pages_list}

---
_This PR was automatically generated by the docs generator workflow._
"""


def _try_add_label(token: str, owner: str, repo_name: str, pr_number: int, label: str) -> None:
    """Attempt to add a label to a PR; silently skip if the label does not exist."""
    url = f"https://api.github.com/repos/{owner}/{repo_name}/issues/{pr_number}/labels"
    try:
        _api_request(url, token, method="POST", payload=[label])
    except GitHubAPIError as exc:
        print(f"Note: could not add label '{label}' (HTTP {exc.status_code}) — continuing without it.")


def _try_enable_auto_merge(token: str, owner: str, repo_name: str, pr_number: int) -> None:
    """Enable auto-merge (squash) on a PR via the GraphQL API."""
    import urllib.request
    import urllib.error

    # Get the PR node ID via REST
    pr_url = f"https://api.github.com/repos/{owner}/{repo_name}/pulls/{pr_number}"
    try:
        pr_data = _api_request(pr_url, token)
        node_id = pr_data.get("node_id")
    except GitHubAPIError as exc:
        print(f"Note: could not fetch PR node ID for auto-merge ({exc}) — continuing without it.")
        return

    if not node_id:
        return

    # Enable auto-merge via GraphQL
    graphql_url = "https://api.github.com/graphql"
    query = """
    mutation EnableAutoMerge($prId: ID!) {
      enablePullRequestAutoMerge(input: {pullRequestId: $prId, mergeMethod: SQUASH}) {
        pullRequest { autoMergeRequest { enabledAt } }
      }
    }
    """
    payload = json.dumps({"query": query, "variables": {"prId": node_id}}).encode("utf-8")
    req = urllib.request.Request(
        graphql_url,
        data=payload,
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=_REQUEST_TIMEOUT) as resp:
            result = json.loads(resp.read().decode("utf-8"))
            if "errors" in result:
                print(f"Note: could not enable auto-merge: {result['errors'][0].get('message', '')} — continuing without it.")
            else:
                print("Auto-merge (squash) enabled on PR.")
    except (urllib.error.HTTPError, urllib.error.URLError) as exc:
        print(f"Note: could not enable auto-merge ({exc}) — continuing without it.")


def _cleanup_stale_branches(token: str, owner: str, repo_name: str, current_branch: str) -> None:
    """Delete remote docs/* branches whose PRs are merged or closed."""
    # List remote docs/* branches
    result = subprocess.run(
        ["git", "ls-remote", "--heads", "origin", "refs/heads/docs/*"],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return

    for line in result.stdout.strip().splitlines():
        if not line:
            continue
        ref = line.split("\t")[-1].replace("refs/heads/", "")
        if ref == current_branch:
            continue

        # Check if there's a closed/merged PR for this branch
        search_url = (
            f"https://api.github.com/repos/{owner}/{repo_name}/pulls"
            f"?head={owner}:{ref}&state=all&per_page=1"
        )
        try:
            prs = _api_request(search_url, token)
        except GitHubAPIError:
            continue

        # Delete if PR is merged/closed, or if there's no PR at all (orphaned branch)
        should_delete = not prs or prs[0].get("state") == "closed"
        if should_delete:
            del_result = subprocess.run(
                ["git", "push", "origin", "--delete", ref],
                capture_output=True,
                text=True,
            )
            if del_result.returncode == 0:
                print(f"Deleted stale branch: {ref}")
            else:
                print(f"Note: could not delete branch {ref}: {del_result.stderr.strip()}")


def _parse_repo(repo_env: str) -> tuple[str, str]:
    """Parse and validate GITHUB_REPOSITORY into (owner, repo_name)."""
    if not repo_env or "/" not in repo_env:
        raise GitOpsConfigError(
            f"GITHUB_REPOSITORY must be in 'owner/repo' format, got: {repo_env!r}"
        )
    owner, repo_name = repo_env.split("/", 1)
    if not owner or not repo_name:
        raise GitOpsConfigError(
            f"GITHUB_REPOSITORY must be in 'owner/repo' format, got: {repo_env!r}"
        )
    return owner, repo_name


def open_pr(bundle_root: str = "./bundle") -> None:
    """
    Push the current branch and open a pull request.

    Raises GitOpsConfigError for missing/invalid configuration.
    Raises GitCommandError for git failures.
    Raises GitHubAPIError for GitHub API failures.
    """
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY")

    if not token:
        raise GitOpsConfigError("GITHUB_TOKEN environment variable is required")
    if not repo:
        raise GitOpsConfigError("GITHUB_REPOSITORY environment variable is required")

    owner, repo_name = _parse_repo(repo)
    branch = _get_current_branch()

    # Load bundle metadata
    manifest = {}
    changed_pages = []
    bundle_path = Path(bundle_root)

    manifest_path = bundle_path / "manifest.json"
    if manifest_path.exists():
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass

    changed_path = bundle_path / "changed_pages.json"
    if changed_path.exists():
        try:
            changed_pages = json.loads(changed_path.read_text(encoding="utf-8")).get("pages", [])
        except (json.JSONDecodeError, OSError):
            pass

    _push_branch(branch)

    # Detect default branch
    result = subprocess.run(
        ["git", "remote", "show", "origin"],
        capture_output=True, text=True
    )
    default_branch = "main"
    for line in result.stdout.splitlines():
        if "HEAD branch:" in line:
            default_branch = line.split("HEAD branch:")[-1].strip()
            break

    pr_title = "Update generated documentation"
    pr_body = _build_pr_body(manifest, changed_pages)

    # Create PR with retries for transient failures
    url = f"https://api.github.com/repos/{owner}/{repo_name}/pulls"
    payload = {
        "title": pr_title,
        "body": pr_body,
        "head": branch,
        "base": default_branch,
    }

    last_error = None
    for attempt in range(_PR_CREATE_RETRIES):
        try:
            pr_data = _api_request(url, token, method="POST", payload=payload)
            break
        except GitHubAPIError as exc:
            last_error = exc
            if exc.status_code and exc.status_code < 500:
                raise  # Client errors are not retryable
            if attempt < _PR_CREATE_RETRIES - 1:
                print(f"PR creation attempt {attempt + 1} failed ({exc}), retrying...")
                time.sleep(_PR_RETRY_DELAY)
    else:
        raise last_error  # type: ignore[misc]

    pr_url = pr_data.get("html_url", "")
    pr_number = pr_data.get("number")
    print(f"Pull request opened: {pr_url}")

    if pr_number:
        _try_add_label(token, owner, repo_name, pr_number, "generated-docs")
        _try_enable_auto_merge(token, owner, repo_name, pr_number)

    # Clean up stale docs/* branches from previous runs
    _cleanup_stale_branches(token, owner, repo_name, branch)


def main():
    parser = argparse.ArgumentParser(description="Push branch and open a pull request.")
    parser.add_argument("--bundle-root", default="./bundle", help="Path to bundle directory")
    args = parser.parse_args()
    try:
        open_pr(args.bundle_root)
    except (GitCommandError, GitHubAPIError, GitOpsConfigError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
