#!/usr/bin/env python3
"""
Push the current branch and open a pull request via the GitHub API.

Usage:
    python tools/docs/gitops/open_pr.py [--bundle-root ./bundle]

Environment variables:
    GITHUB_TOKEN      - Required; GitHub token with repo write access
    GITHUB_REPOSITORY - Required; owner/repo (e.g. JeffSteinbok/octo-docs)
"""

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path


def _get_current_branch() -> str:
    result = subprocess.run(
        ["git", "rev-parse", "--abbrev-ref", "HEAD"],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _push_branch(branch: str) -> None:
    result = subprocess.run(
        ["git", "push", "--set-upstream", "origin", branch],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"Error pushing branch: {result.stderr}", file=sys.stderr)
        sys.exit(1)


def _build_pr_body(manifest: dict, changed_pages: list) -> str:
    commit = manifest.get("commit", "unknown")
    version = manifest.get("bundle_version", "unknown")
    generated_at = manifest.get("generated_at", "unknown")

    pages_list = "\n".join(f"- `{p}`" for p in changed_pages) if changed_pages else "_none_"

    return f"""## Generated Documentation Update

| Field | Value |
|-------|-------|
| Bundle commit | `{commit}` |
| Bundle version | `{version}` |
| Generated at | `{generated_at}` |

### Regenerated pages

{pages_list}

---
_This PR was automatically generated by the docs generator workflow._
"""


def _try_add_label(token: str, owner: str, repo_name: str, pr_number: int, label: str) -> None:
    """Attempt to add a label to a PR; silently skip if the label does not exist."""
    import urllib.request
    import urllib.error

    url = f"https://api.github.com/repos/{owner}/{repo_name}/issues/{pr_number}/labels"
    payload = json.dumps([label]).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=payload,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req):
            pass
    except urllib.error.HTTPError as exc:
        print(f"Note: could not add label '{label}' (HTTP {exc.code}) — continuing without it.")


def open_pr(bundle_root: str = "./bundle") -> None:
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY")

    if not token:
        print("Error: GITHUB_TOKEN environment variable is required", file=sys.stderr)
        sys.exit(1)
    if not repo:
        print("Error: GITHUB_REPOSITORY environment variable is required", file=sys.stderr)
        sys.exit(1)

    branch = _get_current_branch()

    # Load bundle metadata
    manifest = {}
    changed_pages = []
    bundle_path = Path(bundle_root)

    manifest_path = bundle_path / "manifest.json"
    if manifest_path.exists():
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except Exception:
            pass

    changed_path = bundle_path / "changed_pages.json"
    if changed_path.exists():
        try:
            changed_pages = json.loads(changed_path.read_text(encoding="utf-8")).get("pages", [])
        except Exception:
            pass

    _push_branch(branch)

    # Detect default branch
    result = subprocess.run(
        ["git", "remote", "show", "origin"],
        capture_output=True, text=True
    )
    default_branch = "main"
    for line in result.stdout.splitlines():
        if "HEAD branch:" in line:
            default_branch = line.split("HEAD branch:")[-1].strip()
            break

    pr_title = "Update generated documentation"
    pr_body = _build_pr_body(manifest, changed_pages)

    try:
        import urllib.request
        import urllib.error

        owner, repo_name = repo.split("/", 1)
        url = f"https://api.github.com/repos/{owner}/{repo_name}/pulls"
        payload = json.dumps({
            "title": pr_title,
            "body": pr_body,
            "head": branch,
            "base": default_branch,
        }).encode("utf-8")

        req = urllib.request.Request(
            url,
            data=payload,
            headers={
                "Authorization": f"Bearer {token}",
                "Accept": "application/vnd.github+json",
                "Content-Type": "application/json",
                "X-GitHub-Api-Version": "2022-11-28",
            },
            method="POST",
        )
        with urllib.request.urlopen(req) as resp:
            pr_data = json.loads(resp.read().decode("utf-8"))
            pr_url = pr_data.get("html_url", "")
            pr_number = pr_data.get("number")
            print(f"Pull request opened: {pr_url}")

        # Attempt to add the label separately; skip if it doesn't exist
        if pr_number:
            _try_add_label(token, owner, repo_name, pr_number, "generated-docs")
    except Exception as exc:
        print(f"Error opening PR: {exc}", file=sys.stderr)
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(description="Push branch and open a pull request.")
    parser.add_argument("--bundle-root", default="./bundle", help="Path to bundle directory")
    args = parser.parse_args()
    open_pr(args.bundle_root)


if __name__ == "__main__":
    main()
